name: network_stats
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

dependencies:
  args: ^2.3.0
  collection: ^1.17.1
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
  isolator: ^2.0.3
  json_annotation: ^4.8.1
  logger: ^1.4.0
  neat_periodic_task: ^2.0.1
  riverpod: ^2.3.6
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  stack_trace: ^1.11.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
